2018-06-05 12:39:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:39:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:39:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:40:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:40:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:40:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:40:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:41:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:41:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:41:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:41:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:42:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:42:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:42:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:42:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:43:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:43:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:43:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:44:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:44:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:44:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:44:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:45:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:45:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:45:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:45:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:46:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:46:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:46:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:46:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:47:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:47:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:47:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:48:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:48:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:48:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:48:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:49:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:49:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:49:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:49:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:50:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:50:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:50:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:50:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:51:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:51:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:51:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:52:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:52:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:52:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:52:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:53:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:53:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:53:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:53:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:54:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:54:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:54:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:54:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:55:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:55:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:55:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:56:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:56:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:56:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:56:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:57:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:57:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:57:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:57:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:58:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:58:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:58:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:58:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:59:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:59:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 12:59:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:00:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:00:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:00:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:00:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:01:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:01:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:01:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:01:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:02:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:02:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:02:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:02:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:03:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:03:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:03:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:04:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:04:12 ERROR (MainThread) [aiohttp.access] Error in logging
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 501, in __get__
    return inst._cache[self.name]
KeyError: 'remote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 465, in log
    for key, value in fmt_info:
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 457, in <genexpr>
    for key, method in self._methods)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 415, in _format_a
    ip = request.remote
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 503, in __get__
    val = self.wrapped(inst)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_request.py", line 332, in remote
    peername = self.transport.get_extra_info('peername')
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 306, in get_extra_info
    return self._ssl_protocol._get_extra_info(name, default)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 546, in _get_extra_info
    return self._transport.get_extra_info(name, default)
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
2018-06-05 13:04:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:04:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:04:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:05:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:05:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:05:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:05:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:06:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:06:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:06:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:06:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:07:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:07:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:07:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:08:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:08:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:08:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:08:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:09:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:09:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:09:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:09:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:10:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:10:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:10:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:10:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:11:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:11:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:11:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:12:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:12:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:12:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:12:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:13:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:13:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:13:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:13:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:14:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:14:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:14:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:14:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:15:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:15:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:15:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:16:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:16:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:16:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:16:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:17:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:17:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:17:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:17:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:18:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:18:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:18:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:18:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:19:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:19:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:19:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:20:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:20:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:20:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:20:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:21:00 WARNING (Thread-19) [netdisco.ssdp] Error fetching description at http://192.168.1.77:41111/sony/webapi/ssdp/dd.xml
2018-06-05 13:21:00 WARNING (Thread-19) [netdisco.ssdp] Error fetching description at http://192.168.1.77:2226/dd.xml
2018-06-05 13:21:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:21:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:21:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:21:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:22:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:22:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:22:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:22:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:23:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:23:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:23:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:24:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:24:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:24:34 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:24:50 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:25:06 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:25:22 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:25:38 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:25:54 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:26:10 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:26:26 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:26:42 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:26:58 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:27:14 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:27:30 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:27:46 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:28:02 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:28:18 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:28:33 ERROR (MainThread) [homeassistant.components.cloud] Error fetching Cognito keyset: 
2018-06-05 13:39:07 ERROR (MainThread) [homeassistant.components.updater] Could not contact Home Assistant Update to check for updates
2018-06-05 14:25:16 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 113] No route to host
2018-06-05 14:25:16 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 113] No route to host
2018-06-05 15:03:40 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
2018-06-05 15:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
2018-06-05 15:52:50 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
2018-06-05 15:58:17 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
2018-06-05 17:14:42 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 17:24:44 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 18:44:18 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 19:20:43 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 19:50:27 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 20:02:27 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 20:32:35 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 21:14:29 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 21:48:46 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 22:10:48 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 22:34:07 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 22:38:52 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 22:59:52 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 23:34:03 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-05 23:45:21 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 00:02:16 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 00:20:54 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 00:48:38 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 01:04:43 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 04:04:12 ERROR (MainThread) [aiohttp.access] Error in logging
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 501, in __get__
    return inst._cache[self.name]
KeyError: 'remote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 465, in log
    for key, value in fmt_info:
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 457, in <genexpr>
    for key, method in self._methods)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 415, in _format_a
    ip = request.remote
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 503, in __get__
    val = self.wrapped(inst)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_request.py", line 332, in remote
    peername = self.transport.get_extra_info('peername')
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 306, in get_extra_info
    return self._ssl_protocol._get_extra_info(name, default)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 546, in _get_extra_info
    return self._transport.get_extra_info(name, default)
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
2018-06-06 04:12:28 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 04:42:37 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 04:42:40 ERROR (Thread-22) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-06-06 06:12:17 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 06:24:07 ERROR (MainThread) [aiohttp.access] Error in logging
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 501, in __get__
    return inst._cache[self.name]
KeyError: 'remote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 465, in log
    for key, value in fmt_info:
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 457, in <genexpr>
    for key, method in self._methods)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 415, in _format_a
    ip = request.remote
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/helpers.py", line 503, in __get__
    val = self.wrapped(inst)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/web_request.py", line 332, in remote
    peername = self.transport.get_extra_info('peername')
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 306, in get_extra_info
    return self._ssl_protocol._get_extra_info(name, default)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 546, in _get_extra_info
    return self._transport.get_extra_info(name, default)
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
2018-06-06 06:26:08 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
2018-06-06 07:20:48 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 08:44:58 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 08:59:36 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 09:52:28 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 11:00:30 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 11:09:39 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 11:39:15 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 12:16:41 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 13:39:06 ERROR (MainThread) [homeassistant.components.updater] Could not contact Home Assistant Update to check for updates
2018-06-06 15:44:13 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 16:38:53 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 16:38:56 ERROR (Thread-22) [pychromecast.socket_client] Failed to connect, retrying in 5.0s
2018-06-06 16:49:50 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 17:15:32 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 18:01:54 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 18:11:52 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 18:18:31 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 18:54:10 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 19:05:42 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 19:33:01 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 19:41:39 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 19:55:54 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 20:13:09 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 20:42:02 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 21:09:05 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 21:29:53 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 21:36:14 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 21:47:04 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 21:56:53 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 22:28:10 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 23:00:05 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 23:20:47 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-06 23:31:15 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 00:11:10 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 00:27:05 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 01:00:41 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 01:15:16 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 01:50:53 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 01:57:14 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 03:36:57 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 03:51:16 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 03:59:34 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 04:28:36 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 05:31:21 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 06:01:59 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 06:12:13 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 07:12:52 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 07:45:52 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 11:26:41 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 11:45:24 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 12:23:45 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 13:18:06 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 13:39:06 ERROR (MainThread) [homeassistant.components.updater] Could not contact Home Assistant Update to check for updates
2018-06-07 14:11:44 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 14:48:23 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 15:10:24 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 16:43:26 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 16:53:27 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 17:04:36 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 17:20:50 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 18:18:43 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 18:49:51 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 19:21:22 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 19:45:04 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 20:16:35 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 20:31:35 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 20:44:47 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 20:53:37 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 21:02:05 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 21:07:52 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 21:08:32 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 21:24:11 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 21:34:34 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
2018-06-07 22:23:36 WARNING (Thread-22) [pychromecast.socket_client] Heartbeat timeout, resetting connection
